local configs = {
  ensure_installed = {
    "bash",
    "c",
    "css",
    "go",
    "gomod",
    "gosum",
    "gowork",
    "html",
    "http",
    "java",
    "javascript",
    "json",
    "jsonc",
    "jsdoc",
    "lua",
    "luap",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    "rust",
    "sql",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vimdoc",
    "xml",
  },
  sync_install = false,
  highlight = { enable = true },
  indent = { enable = true },
  auto_install = true,
}

require("nvim-treesitter.configs").setup(configs)
